### ISSUE TITLE
include in stackage?

### ISSUE THREAD

**Issue by alexanderkjeldaas** [christian-marie/git-vogue#101]
would it be possible to include this tool in stackage?

**Comment by christian-marie** [comment]
I've been meaning to, I'm not sure what it involves. I'll take a look this weekend, time permitting.

**Comment by christian-marie** [comment]
I will definitely continue to consider this a great thing to do

**Comment by christian-marie** [comment]
Forever

**Comment by christian-marie** [comment]
Still planning to do this! One day.

**Comment by christian-marie** [comment]
OK, the hard work of updating all of the things to work with the latest stack LTS is done. We now only support building on cabal >2, but, who cares right? This isn't a compile-time dependency, it's a utility. I shall work out what's required for adding to stackage now.

**Comment by christian-marie** [comment]
Here is a PR for stackage: https://github.com/fpco/stackage/pull/3625

**Comment by christian-marie** [comment]
And merged! It should appear in stackage some day.
