### ISSUE TITLE
Transfer or delete repo?

### ISSUE THREAD

**Issue by thsutton** [christian-marie/git-vogue#91]
@oswynb has a fork of this repo and is maintaining the package published on Hackage.

Maybe this repo should be deleted or transferred to him?

/cc @christian-marie

**Comment by ctd** [comment]
I'm happy to enact either.

**Comment by christian-marie** [comment]
@thsutton Perhaps we could create a github repo with all of the Haskell code that would otherwise die, move all of the things to that place, then add as maintainers:

@thsutton, @tvh, @glasnt, @thsutton, @oswynb, @olorin, @tranma.

This incurs the overhead of deciding on an organisation's name, though. I suggest: https://github.com/organizations/WhereSoftwareGoesToDie

**Comment by olorin** [comment]
> Perhaps we could create a github repo with all of the Haskell code that would otherwise die, move all of the things to that place, then add as maintainers: 

This works for me. Though in this case if @oswynb is maintaining/wants to take ownership of `git-vogue` I'd also be happy with transferring it to him (the organisation idea works for the rest of the Haskell repositories though).

**Comment by christian-marie** [comment]
@oswynb? Would you like git-vogue transferred to you, or to an organisation?

**Comment by oswynb** [comment]
Probably easiest if it just all goes into an organisation methinks.

**Comment by christian-marie** [comment]
@ctd whenever you're ready, I've invited you as an owner to https://github.com/organizations/WhereSoftwareGoesToDie

**Comment by ctd** [comment]
@christian-marie ack. We'll be reviewing this (and other) repos soon with a view to transfer their ownership there.

**Comment by christian-marie** [comment]
Moved it to my account.

**Comment by christian-marie** [comment]
Oh... I just realised that @oswynb has a fork. Now we have a fork when we don't need a fork

@oswynb I am happy to maintain this, happy for you to also, but we should kill the fork.

It signals a lack of communication, doesn't help collaboration, dilutes traffic, etc.

@oswynb I'll add you as a maintainer, we can merge any changes from your fork back in, then if you want it under your account we can transfer it. Sound OK?

**Comment by oswynb** [comment]
happy for you to own it, merge away

**Comment by christian-marie** [comment]
Great, nothing more to do then!

Forgot to thank you for maintaining the fork, too, thanks. You should be a collaborator on this repo now. Feel free to treat it as you did your fork, I'll likely be working on this a little in the near future.
